### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by abargnesi**
Hi there! :wave:

Great project!

**What**

This PR upgrades the compile and test dependencies for *jInstagram*.

The upgrade resulted in all dependencies being upgraded to the latest version. The test suite passes with the same outcome (`Tests run: 526, Failures: , Errors: 0, Skipped: 19`) as on master. The cobertura code coverage was also run (`mvn clean cobertura:cobertura cobertura:dump-datafile`) and code coverage percentages and counts were the same as master.

**Why**

Upgrading dependencies ensures that conflicts happen less often when integrating into other projects. This was my motivation.

----

Details on the changes were added for each commit.

### CODE REVIEW

**Comment by abargnesi** [comment]
Oh no on the loss in coverage. My changes to tests seemed minor. Any ideas @sachin-handiekar?

**Comment by abargnesi** [comment]
I believe the reduction in code coverage is due to removal of unused mocks in fbe2275. The unused mocks were not adding much for code coverage.

Can this be merged? Do you see anything wrong?

**Comment by sachin-handiekar** [comment]
Thanks for the PR!!!

**Comment by sachin-handiekar** [comment]
will merge it today

**Comment by abargnesi** [comment]
Thanks! :+1:

**Comment by abargnesi** [comment]
:tada: thank you!

**Pull request merged**
