### PR TITLE
Media carousel

### PR DESCRIPTION
**Pull request by jcodagnone**
Add support for medias like https://www.instagram.com/p/BQ0eAlwhDrw/

### CODE REVIEW

**Comment by abargnesi** [comment]
Thanks! Nice and timely contribution.

Does it make sense to use `MediaFeedData` to represent media in a carousel? A lot of fields will be `null` from what I see. Maybe a new model object named `CarouselMedia`?

Here is the JSON schema for carousel media:

```
"carousel_media": {
  "items": {
    "properties": {
      "images": {
        "properties": {
          "low_resolution": {
            "properties": {
              "height": {
                "type": "integer"
              },
              "url": {
                "type": "string"
              },
              "width": {
                "type": "integer"
              }
            },
            "required": [
              "height",
              "url",
              "width"
            ],
            "type": "object"
          },
          "standard_resolution": {
            "properties": {
              "height": {
                "type": "integer"
              },
              "url": {
                "type": "string"
              },
              "width": {
                "type": "integer"
              }
            },
            "required": [
              "height",
              "url",
              "width"
            ],
            "type": "object"
          },
          "thumbnail": {
            "properties": {
              "height": {
                "type": "integer"
              },
              "url": {
                "type": "string"
              },
              "width": {
                "type": "integer"
              }
            },
            "required": [
              "height",
              "url",
              "width"
            ],
            "type": "object"
          }
        },
        "required": [
          "low_resolution",
          "standard_resolution",
          "thumbnail"
        ],
        "type": "object"
      },
      "type": {
        "type": "string"
      },
      "users_in_photo": {
        "items": {},
        "type": "array"
      },
      "videos": {
        "properties": {
          "low_bandwidth": {
            "properties": {
              "height": {
                "type": "integer"
              },
              "url": {
                "type": "string"
              },
              "width": {
                "type": "integer"
              }
            },
            "required": [
              "height",
              "url",
              "width"
            ],
            "type": "object"
          },
          "low_resolution": {
            "properties": {
              "height": {
                "type": "integer"
              },
              "url": {
                "type": "string"
              },
              "width": {
                "type": "integer"
              }
            },
            "required": [
              "height",
              "url",
              "width"
            ],
            "type": "object"
          },
          "standard_resolution": {
            "properties": {
              "height": {
                "type": "integer"
              },
              "url": {
                "type": "string"
              },
              "width": {
                "type": "integer"
              }
            },
            "required": [
              "height",
              "url",
              "width"
            ],
            "type": "object"
          }
        },
        "required": [
          "low_bandwidth",
          "low_resolution",
          "standard_resolution"
        ],
        "type": "object"
      }
    },
    "required": [
      "type",
      "users_in_photo"
    ],
    "type": "object"
  },
  "type": "array"
}
```

**Comment by jcodagnone** [comment]
Hi @abargnesi ,

I make myself the same question. I decided to reuse MediaFeedData  as it was simple and I didn't have to refactor any code, but sure I can change that!

**Comment by abargnesi** [comment]
Thanks. I think a new model object here makes the available data properties explicit. Downstream code wouldn't need to check `MediaFeedData.getType()` in order to determine object state.

**Comment by sachin-handiekar** [comment]
@jcodagnone Are you working on creating a new object model ?? Or should I merge the PR in the master ??

**Comment by abargnesi** [comment]
@jcodagnone If you want I can update the model classes in a followup PR after this one is merged.

**Pull request merged**
