### PR TITLE
Decouple requests and serialization from authentication and signing

### PR DESCRIPTION
**Pull request by sigpwned**
My team has started using a proxy for all API data collection for tracking purposes. The jInstagram proxy feature works great for that! However, we've taken the proxy one step further by having it handle authentication (by managing our access tokens) and signing, too. As a result, in order to keep using jInstagram, we need some way to send unauthenticated, unsigned requests to our proxy. That requires a couple of simple changes to tease apart the core API functionality -- basically HTTP requests and serialization -- from the authentication and signing code. In this pull request, I've moved the core functionality out of `Instagram` into a new abstract base class `InstagramBase`, leaving only the authentication and signing code in `Instagram`. The change is completely backwards compatible, but will allow my team to create an "unauthenticated" instagram client by subclassing `InstagramBase`.

Hopefully that description makes sense! Please shoot any questions my way!

Thanks for all your great work making an Instagram library that's so easy to use. :)

### CODE REVIEW

**Comment by sigpwned** [comment]
Not sure why the test coverage has decreased so much. This change more or less only moves code around! :-/

**Comment by sigpwned** [comment]
I've made one additional change, which is to pull out an `InstagramClient` interface, which provides users a flexible way to pass around `Instagram` objects for doing work that will support any subclass of the unauthenticated `InstagramBase`, including the default `Instagram` object. Moving to an interface-based approach will also allow users to adopt some more sophisticated techniques, like dynamic proxies, so there are some other benefits, too!

**Comment by sigpwned** [comment]
Thank you so much for merging my pull request! Do you have the next jInstagram release planned? My team is anxious to integrate the changes from Maven Central! 😄

**Comment by sachin-handiekar** [comment]
I've released the library in maven central - https://mvnrepository.com/artifact/com.sachinhandiekar/jInstagram/1.1.8

**Comment by sigpwned** [comment]
Thank you!

**Pull request merged**
