### PR TITLE
Add space to temporarily fix broken access_token extraction

### PR DESCRIPTION
**Pull request by alexanderzafirov**

### CODE REVIEW

**Comment by sachin-handiekar** [comment]
I think #151 will fix the problem. Have to run some test against it, will let you know once I do it.

**Comment by alexanderzafirov** [comment]
@sachin-handiekar that's even better!

**Comment by alexanderzafirov** [comment]
@sachin-handiekar I saw that you merged #151. Did you upload the artifact so I can pull it in?

**Comment by sachin-handiekar** [comment]
@alexanderzafirov I've pushed the artifact in Maven central. might take some time to become available publicly..

**Pull request closed without merging**
