### PR TITLE
Added test to InstagramBase

### PR DESCRIPTION
**Pull request by marcbr8**
Tests retry logic of https://github.com/sachin-handiekar/jInstagram/pull/186

### CODE REVIEW

**Comment by abargnesi** [comment]
I ran this test on master with your PR commits and the test is failing for me. Any ideas?

When I run `mvn clean install` (like travis did) I receive:

```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.sachinhandiekar:jInstagram:jar:1.1.9-SNAPSHOT
[WARNING] 'parent.relativePath' of POM com.sachinhandiekar:jInstagram:1.1.9-SNAPSHOT (/home/tony/work/jInstagram/pom.xml) points at com.crimsonhexagon:forsight instead of org.sonatype.oss:oss-parent, please verify your project structure @ line 3, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building jInstagram 1.1.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jInstagram ---
[INFO] Deleting /home/tony/work/jInstagram/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jInstagram ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jInstagram ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/tony/work/jInstagram/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ jInstagram ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 85 source files to /home/tony/work/jInstagram/target/classes
[WARNING] /home/tony/work/jInstagram/src/main/java/org/jinstagram/InstagramClient.java: Some input files use or override a deprecated API.
[WARNING] /home/tony/work/jInstagram/src/main/java/org/jinstagram/InstagramClient.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jInstagram ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ jInstagram ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 78 source files to /home/tony/work/jInstagram/target/test-classes
[WARNING] /home/tony/work/jInstagram/src/test/java/org/jinstagram/InstagramTest.java: Some input files use or override a deprecated API.
[WARNING] /home/tony/work/jInstagram/src/test/java/org/jinstagram/InstagramTest.java: Recompile with -Xlint:deprecation for details.
[WARNING] /home/tony/work/jInstagram/src/test/java/org/jinstagram/entity/locations/LocationSearchFeedTest.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/tony/work/jInstagram/src/test/java/org/jinstagram/entity/locations/LocationSearchFeedTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ jInstagram ---
[INFO] Surefire report directory: /home/tony/work/jInstagram/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jinstagram.http.ResponseTest
null
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.17 sec
Running org.jinstagram.http.URLUtilsTest
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running org.jinstagram.http.VerbsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.http.StreamUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.http.APILimitUtilsTest
06:57:54.601 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Limit, value :null
06:57:54.602 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Remaining, value :null
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.044 sec
Running org.jinstagram.http.HttpStatusTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running org.jinstagram.http.RequestTest
Mock for HttpURLConnection, hashCode: 1475491159
Tests run: 37, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.034 sec
Running org.jinstagram.auth.InstagramApiTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.jinstagram.auth.exceptions.OAuthExceptionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.auth.exceptions.OAuthParametersMissingExceptionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.auth.InstagramAuthServiceTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.jinstagram.auth.model.TokenTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.auth.model.OAuthConfigTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running org.jinstagram.auth.model.VerifierTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.auth.model.OAuthRequestTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.common.LocationTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
Running org.jinstagram.entity.common.VideosTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec
Running org.jinstagram.entity.common.GridPositionTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.entity.common.InstagramErrorResponseTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec
Running org.jinstagram.entity.common.PaginationTest
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running org.jinstagram.entity.common.UsersInPhotoTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.common.CaptionTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running org.jinstagram.entity.common.MetaTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.jinstagram.entity.common.LikesTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.common.CommentsTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.common.ImageDataTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
Running org.jinstagram.entity.common.VideoDataTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec
Running org.jinstagram.entity.common.ImagesTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.common.UserTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.jinstagram.entity.common.FromTagDataTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.locations.LocationInfoTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.locations.LocationSearchFeedTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.likes.LikesFeedTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.entity.users.basicinfo.UserInfoTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.users.basicinfo.CountsTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.users.basicinfo.UserInfoDataTest
Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.jinstagram.entity.users.feed.MediaFeedTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.users.feed.UserFeedDataTest
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.jinstagram.entity.users.feed.UserFeedTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.entity.users.feed.MediaFeedDataTest
Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
Running org.jinstagram.entity.oembed.OembedInformationTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running org.jinstagram.entity.relationships.RelationshipFeedTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.entity.relationships.RelationshipDataTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.entity.media.MediaInfoFeedTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.tags.TagMediaFeedTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.tags.TagInfoFeedTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.entity.tags.TagInfoDataTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.entity.tags.TagSearchFeedTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.comments.CommentDataTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.comments.MediaCommentResponseTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.entity.comments.MediaCommentsFeedTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.exceptions.InstagramExceptionTest
06:57:54.725 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Limit, value :null
06:57:54.725 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Remaining, value :null
06:57:54.725 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Limit, value :null
06:57:54.725 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Remaining, value :null
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.exceptions.InstagramRateLimitExceptionTest
06:57:54.726 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Limit, value :null
06:57:54.726 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Remaining, value :null
06:57:54.726 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Limit, value :null
06:57:54.726 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Remaining, value :null
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.exceptions.InstagramBadRequestExceptionTest
06:57:54.727 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Limit, value :null
06:57:54.727 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Remaining, value :null
06:57:54.727 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Limit, value :null
06:57:54.727 [main] ERROR org.jinstagram.http.APILimitUtils - Invalid Integer value for key: X-Ratelimit-Remaining, value :null
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.InstagramTest
06:57:54.729 [main] ERROR org.jinstagram.InstagramTest - No access token found...
06:57:54.731 [main] ERROR org.jinstagram.InstagramTest - No access token found...
06:57:54.731 [main] ERROR org.jinstagram.InstagramTest - No access token found...
06:57:54.731 [main] ERROR org.jinstagram.InstagramTest - No access token found...
06:57:54.731 [main] ERROR org.jinstagram.InstagramTest - No access token found...
06:57:54.732 [main] ERROR org.jinstagram.InstagramTest - No access token found...
06:57:54.732 [main] ERROR org.jinstagram.InstagramTest - No access token found...
06:57:54.732 [main] ERROR org.jinstagram.InstagramTest - No access token found...
06:57:54.732 [main] ERROR org.jinstagram.InstagramTest - No access token found...
Tests run: 15, Failures: 0, Errors: 0, Skipped: 15, Time elapsed: 0.003 sec
Running org.jinstagram.model.ConstantsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.model.ScopeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.model.MethodsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.model.QueryParamTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.model.RelationshipTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.realtime.SubscriptionsListResponseTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.realtime.SubscriptionUtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec
Running org.jinstagram.realtime.SubscriptionTypeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.realtime.ConstantsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.realtime.SubscriptionResponseObjectTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.realtime.SubscriptionResponseDataTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.realtime.InstagramSubscriptionTest
Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.realtime.SubscriptionResponseTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.jinstagram.InstagramBaseTest
06:57:55.679 [main] DEBUG org.jinstagram.InstagramBase - Creating request for Instagram -  null
06:57:55.695 [main] DEBUG org.jinstagram.InstagramBase - Creating request for Instagram -  null
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.956 sec <<< FAILURE!
shouldGetMediaCommentsFeedWithoutRetrying(org.jinstagram.InstagramBaseTest)  Time elapsed: 0.242 sec  <<< ERROR!
java.lang.NullPointerException
	at org.jinstagram.Instagram.request(Instagram.java:121)
	at org.jinstagram.Instagram.request(Instagram.java:23)
	at org.jinstagram.InstagramBase.getApiResponse(InstagramBase.java:997)
	at org.jinstagram.InstagramBase.createInstagramObject(InstagramBase.java:843)
	at org.jinstagram.InstagramBase.createInstagramObject(InstagramBase.java:929)
	at org.jinstagram.InstagramBase.getMediaComments(InstagramBase.java:504)
	at org.jinstagram.InstagramBaseTest.whenGettingMediaComments(InstagramBaseTest.java:115)
	at org.jinstagram.InstagramBaseTest.shouldGetMediaCommentsFeedWithoutRetrying(InstagramBaseTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:316)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:300)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:288)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:208)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:121)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:123)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

shouldRetryWhenGetMediaCommentsFeedFailsOnTheFirstTry(org.jinstagram.InstagramBaseTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.NullPointerException
	at org.jinstagram.Instagram.request(Instagram.java:121)
	at org.jinstagram.Instagram.request(Instagram.java:23)
	at org.jinstagram.InstagramBase.getApiResponse(InstagramBase.java:997)
	at org.jinstagram.InstagramBase.createInstagramObject(InstagramBase.java:843)
	at org.jinstagram.InstagramBase.createInstagramObject(InstagramBase.java:929)
	at org.jinstagram.InstagramBase.getMediaComments(InstagramBase.java:504)
	at org.jinstagram.InstagramBaseTest.whenGettingMediaComments(InstagramBaseTest.java:115)
	at org.jinstagram.InstagramBaseTest.shouldRetryWhenGetMediaCommentsFeedFailsOnTheFirstTry(InstagramBaseTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:316)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:300)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:288)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:208)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:121)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:123)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.jinstagram.utils.PreconditionsTest
Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
Running org.jinstagram.utils.EnforceSignedRequestUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.107 sec
Running org.jinstagram.utils.EnforceSignedHeaderUtilsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.jinstagram.utils.MapUtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests in error: 
  shouldGetMediaCommentsFeedWithoutRetrying(org.jinstagram.InstagramBaseTest)
  shouldRetryWhenGetMediaCommentsFeedFailsOnTheFirstTry(org.jinstagram.InstagramBaseTest)

Tests run: 528, Failures: 0, Errors: 2, Skipped: 19

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.919 s
[INFO] Finished at: 2016-12-13T06:57:55-05:00
[INFO] Final Memory: 20M/280M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project jInstagram: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/tony/work/jInstagram/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by marcbr8** [comment]
For Travis and me is working fine. What maven version are you using? Also I would delete the local mockito (and maybe some other dependencies that may clash) repository under `~/.m2/`

**Comment by abargnesi** [comment]
I am running maven *3.3.9*. Removing *mockito*, *powermock*, and *junit* deps from maven repository did not help.

**Comment by marcbr8** [comment]
Any news on this @abargnesi @sachin-handiekar? How come is the coverage decreasing if this PR is only composed of tests?

**Comment by sachin-handiekar** [comment]
@marcbr8 

Hey sorry, Got too busy with my projects... Will look over this during the weekend!!!

Also have to release the project to Maven, it's been a long time I had release the artifact.

Will defn. look over this weekend.

Regards,
Sachin

**Comment by sachin-handiekar** [comment]
I've fixed the ```InstagramBaseTest.java```. It needed the following mock to run properly - 

```java
  when(request.getCharset()).thenReturn("UTF-8");
  when(request.getVerb()).thenReturn(Verbs.GET);
  when(request.getUrl()).thenReturn("/mock/");
```

Will have a look at improving the coverage later on today.

**Comment by abargnesi** [comment]
Nice work @marcbr8 and @sachin-handiekar.

Works for me now.

**Pull request merged**
