### PR TITLE
Bug 192, missing html code in response. Added html and thumbnail...

### PR DESCRIPTION
**Pull request by brennhill**
Added parameters to OembedInformation.java

### CODE REVIEW

**Comment by sachin-handiekar** [comment]
Thnks for the PR!!!

**Comment by brennhill** [comment]
Thank you for the library :-)

**Comment by MallorcaSoftware** [comment]
Would be great if you can release this pr ;)

**Comment by brennhill** [comment]
yes, an official release into the maven repositories would be fantastic.

**Comment by MallorcaSoftware** [comment]
But properly after #196 is fixed. I have to look into the development guide afterwards i can fix it.

**Comment by sachin-handiekar** [comment]
@MallorcaSoftware  Let me know if you fix the problem you've mention in #196 or I'll have a look over it on the weekend (Will also release it on the Maven Central )

**Pull request merged**
